# Generated by scripts/update-browseros. Do not edit by hand.
{
  version = "0.51.0";
  tag = "v0.51.0";
  url = "https://github.com/browseros-ai/BrowserOS/releases/download/v0.51.0/BrowserOS_v0.51.0_x64.AppImage";
  hash = "sha256-tYbfcgg8BG4uotHMG2RjMl7Uywwxl11I4JzBQhXj578=";
}
