# Generated by scripts/update-browseros. Do not edit by hand.
#
# The initial archive deliberately uses lib.fakeHash. Run
# ./scripts/update-browseros before the first build; the updater replaces
# this file atomically with the latest stable BrowserOS release and real hash.
{
  version = "0.50.3";
  tag = "v0.50.3";
  url = "https://github.com/browseros-ai/BrowserOS/releases/download/v0.50.3/BrowserOS_v0.50.3_x64.AppImage";
  hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
}
