# Generated by scripts/update-browseros. Do not edit by hand.
{
  version = "0.50.3";
  tag = "v0.50.3";
  url = "https://github.com/browseros-ai/BrowserOS/releases/download/v0.50.3/BrowserOS_v0.50.3_x64.AppImage";
  hash = "sha256-Foln3alE/zGRYNF/p3hYL5CD5dvXapcouiClPej2DaQ=";
}
